name: dart_lmdb
description: "A LMDB Dart wrapper"
repository: https://github.com/jakobkordez/dart_lmdb
version: 0.9.12+1

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.0
  hooks: ^1.0.1
  logging: ^1.3.0
  native_toolchain_c: ^0.17.0
  path: ^1.9.1

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.28.0
  yaml: ^3.1.3
